//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLMVC.AseguradoraReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AseguradoraReference.IAseguradoraService")]
    public interface IAseguradoraService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradoraService/AddEF", ReplyAction="http://tempuri.org/IAseguradoraService/AddEFResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Usuario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Direccion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Colonia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Municipio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Estado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Pais))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Rol))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Aseguradora))]
        ML.Result AddEF(ML.Aseguradora aseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradoraService/AddEF", ReplyAction="http://tempuri.org/IAseguradoraService/AddEFResponse")]
        System.Threading.Tasks.Task<ML.Result> AddEFAsync(ML.Aseguradora aseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradoraService/UpdateEF", ReplyAction="http://tempuri.org/IAseguradoraService/UpdateEFResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Usuario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Direccion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Colonia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Municipio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Estado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Pais))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Rol))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Aseguradora))]
        ML.Result UpdateEF(ML.Aseguradora aseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradoraService/UpdateEF", ReplyAction="http://tempuri.org/IAseguradoraService/UpdateEFResponse")]
        System.Threading.Tasks.Task<ML.Result> UpdateEFAsync(ML.Aseguradora aseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradoraService/DeleteEF", ReplyAction="http://tempuri.org/IAseguradoraService/DeleteEFResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Aseguradora))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Usuario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Direccion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Colonia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Municipio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Estado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Pais))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Rol))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        ML.Result DeleteEF(int IdAseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradoraService/DeleteEF", ReplyAction="http://tempuri.org/IAseguradoraService/DeleteEFResponse")]
        System.Threading.Tasks.Task<ML.Result> DeleteEFAsync(int IdAseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradoraService/GetByIdEF", ReplyAction="http://tempuri.org/IAseguradoraService/GetByIdEFResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Aseguradora))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Usuario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Direccion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Colonia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Municipio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Estado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Pais))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Rol))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        ML.Result GetByIdEF(int IdAseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradoraService/GetByIdEF", ReplyAction="http://tempuri.org/IAseguradoraService/GetByIdEFResponse")]
        System.Threading.Tasks.Task<ML.Result> GetByIdEFAsync(int IdAseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradoraService/GetAllEF", ReplyAction="http://tempuri.org/IAseguradoraService/GetAllEFResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Aseguradora))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Usuario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Direccion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Colonia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Municipio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Estado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Pais))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Rol))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        ML.Result GetAllEF();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradoraService/GetAllEF", ReplyAction="http://tempuri.org/IAseguradoraService/GetAllEFResponse")]
        System.Threading.Tasks.Task<ML.Result> GetAllEFAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAseguradoraServiceChannel : PLMVC.AseguradoraReference.IAseguradoraService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AseguradoraServiceClient : System.ServiceModel.ClientBase<PLMVC.AseguradoraReference.IAseguradoraService>, PLMVC.AseguradoraReference.IAseguradoraService {
        
        public AseguradoraServiceClient() {
        }
        
        public AseguradoraServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AseguradoraServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AseguradoraServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AseguradoraServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ML.Result AddEF(ML.Aseguradora aseguradora) {
            return base.Channel.AddEF(aseguradora);
        }
        
        public System.Threading.Tasks.Task<ML.Result> AddEFAsync(ML.Aseguradora aseguradora) {
            return base.Channel.AddEFAsync(aseguradora);
        }
        
        public ML.Result UpdateEF(ML.Aseguradora aseguradora) {
            return base.Channel.UpdateEF(aseguradora);
        }
        
        public System.Threading.Tasks.Task<ML.Result> UpdateEFAsync(ML.Aseguradora aseguradora) {
            return base.Channel.UpdateEFAsync(aseguradora);
        }
        
        public ML.Result DeleteEF(int IdAseguradora) {
            return base.Channel.DeleteEF(IdAseguradora);
        }
        
        public System.Threading.Tasks.Task<ML.Result> DeleteEFAsync(int IdAseguradora) {
            return base.Channel.DeleteEFAsync(IdAseguradora);
        }
        
        public ML.Result GetByIdEF(int IdAseguradora) {
            return base.Channel.GetByIdEF(IdAseguradora);
        }
        
        public System.Threading.Tasks.Task<ML.Result> GetByIdEFAsync(int IdAseguradora) {
            return base.Channel.GetByIdEFAsync(IdAseguradora);
        }
        
        public ML.Result GetAllEF() {
            return base.Channel.GetAllEF();
        }
        
        public System.Threading.Tasks.Task<ML.Result> GetAllEFAsync() {
            return base.Channel.GetAllEFAsync();
        }
    }
}
